---
title: "MapApp"
author: "Jose Roriguez"
date: "6/29/2021"
output: html_document
---

```{r}
library('shiny')
library('leaflet')
library('shiny')
library('ggplot2')
library('plyr')
library('dplyr')
library(tigris) #download shp file from U.S. census website
library(rgdal)
library(tmap)
library(tidyverse)
library(reshape)
```


```{r}
CSV_data <- read.csv("AW.DWRdata.csv")
CSV_data <- CSV_data%>%group_by(NAME,Year,Crop)%>%mutate(Total_Land=sum(Total_Land),TW=sum(TW))
CSV_data <- CSV_data%>%group_by(NAME,Year)%>%mutate(`Total land`=sum(Total_Land)/1000,`Total water`=sum(TW)/1000,AW2=TW/Total_Land)%>%ungroup()
Data <- melt(as.data.frame(CSV_data),id=c("NAME","Crop","Year"))
Data <- Data%>%filter(variable!="AW")
Data[Data$variable%in%c("Total water","Total land"),]$Crop = "Sum All"
Data <- Data %>% unique(by=c("NAME","Year","Crop","variable","value"))
Data$variable <- as.character(Data$variable)
Data[Data$variable=="AW2",]$variable = "Applied water by acre"
Data[Data$variable=="Total_Land",]$variable = "Land use"
Data[Data$variable=="TW",]$variable = "Water use"
Data[Data$variable=="Total water",]$variable = "Water use"
Data[Data$variable=="Total land",]$variable = "Land use"
```

# ```{r}
# download.file("https://data.ca.gov/dataset/e212e397-1277-4df3-8c22-40721b095f33/resource/b0007416-a325-4777-9295-368ea6b710e6/download/ca-county-boundaries.zip", destfile = "ca_counties.zip")
# aa <- unzip("ca_counties.zip")
# ```

```{r}
ca_geo<-tigris::counties(state = "ca", class = "sf") 
```

```{r}
Unique_Crops <- unique(Data$Crop)
Unique_Years <- unique(Data$Year)
Unique_Vars <- unique(Data$variable)
```

```{r}
Data2 <- Data%>%filter(Crop=="Corn",Year==2015,variable=="Land use")
ca_geo2 <- geo_join(ca_geo,Data2,"NAME","NAME",how="inner")%>%sf::st_transform(4326)
```

```{r}
popup <- paste0("County: ", ca_geo2$NAME, "<br>", "Total: ", round(ca_geo2$value,2))
pal <- colorNumeric(
  palette = "YlGnBu",
  domain = ca_geo2$value
)
```

```{r}
map1<-leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = ca_geo2, 
              fillColor = ~pal(value), 
              color = "#b2aeae", # you need to use hex colors
              fillOpacity = 0.7, 
              weight = 0.3, 
              smoothFactor = 0.2,
              popup = popup) %>%
  leaflet::addLegend(pal = pal, 
            values = ca_geo2$value, 
            position = "bottomright", 
            title = "by county",
            labFormat = labelFormat(suffix = "")) 
map1
```



```{r}
ui <- fluidPage(
  
  # App title ----
  titlePanel("Water and Land Use Map"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      
     selectInput(inputId="Crop_Chosen", label=" Choose Crop", choices=c(Unique_Crops), selected = NULL, multiple = FALSE),
      selectInput(inputId="Year_Chosen", label=" Choose Year", choices=c(Unique_Years), selected = NULL, multiple = FALSE),
      selectInput(inputId="Year_Chosen", label=" Choose Variable", choices=c(Unique_Vars), selected = NULL, multiple = FALSE),
      
      
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = "tabs",
                  tabPanel("Map", leafletOutput("Cali_Map", height = 600),
                                                p(),))
      
      
      
    
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output, session){
  
  # Reactive expression to generate the requested distribution ----
  # This is called whenever the inputs change. The output functions
  # defined below then use the value computed from this expression
  
  #d <- reactive({
    #radio <- switch(input$radio,
                    #Yp = Coloumns[3],
                    #Ap = Coloumns[4],
                    #Pp = Coloumns[5],
                    #Coloumns[3])
    
    
  #})
  
  
  
  
  # Generate a plot of the data ----
  # Also uses the inputs to build the plot label. Note that the
  # dependencies on the inputs and the data reactive expression are
  # both tracked, and all expressions are called in the sequence
  # implied by the dependency graph.
  output$Cali_Map<- renderLeaflet({
    leaflet(json_cali_file) %>%
      setView(-119, 35, 5) %>%
      addTiles("MapBox", options = providerTileOptions(
        id = "mapbox.light",
        accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))
    
    m %>% addPolygons()
  
  
  })  
}




shinyApp(ui = ui, server = server)
```




