import pandas as pd
import numpy as np

# First, create a dictionary from the mapping data
'''
crop_mapping = {
    'Hay Alfalfa ': 'Alfalfa',
    'Seed Alfalfa ': 'Alfalfa',
    'Alfalfa, All ': 'Alfalfa',
    'Almond Hulls ': 'Almonds & Pistachios',
    'Almonds All ': 'Almonds & Pistachios',
    'Pistachios ': 'Almonds & Pistachios',
    'Corn Silage ': 'Corn',
    'Cotton Lint Pima ': 'Cotton',
    'Cotton Lint Unspecified ': 'Cotton',
    'Cotton Lint Upland ': 'Cotton',
    'Cotton Seed Planting ': 'Cotton',
    'Cottonseed ': 'Cotton',
    'Cucumbers ': 'Cucurbits',
    'Melons Cantaloupe ': 'Cucurbits',
    'Melons Honeydew ': 'Cucurbits',
    'Melons Unspecified ': 'Cucurbits',
    'Melons Watermelon ': 'Cucurbits',
    'Squash ': 'Cucurbits',
    'Melons Casaba ': 'Cucurbits',
    'Melons Crenshaw ': 'Cucurbits',
    'Beans Blackeye (Peas) ': 'Dry Beans',
    'Beans Dry Edible Unspec. ': 'Dry Beans',
    'Beans Fava ': 'Dry Beans',
    'Beans Garbanzo ': 'Dry Beans',
    'Beans Kidney Red ': 'Dry Beans',
    'Beans Lima Lg. Dry ': 'Dry Beans',
    'Beans Lima Unspecified ': 'Dry Beans',
    'Beans Pink ': 'Dry Beans',
    'Beans Seed ': 'Dry Beans',
    'Peas Dry Edible ': 'Dry Beans',
    'Beans Lima Green ': 'Dry Beans',
    'Beans Snap Fresh Market ': 'Dry Beans',
    'Beans Fresh Unspecified ': 'Dry Beans',
    'Beans Snap Unspecified ': 'Dry Beans',
    'Beans Pinto ': 'Dry Beans',
    'Beans Red Small ': 'Dry Beans',
    'Beans Snap Processing ': 'Dry Beans',
    'Beans White Small ': 'Dry Beans',
    'Beans White Small Flat ': 'Dry Beans',
    'Corn Seed ': 'Field',
    'Field Crop By-products ': 'Field',
    'Field Crops Seed Misc. ': 'Field',
    'Peanuts All ': 'Field',
    'Peas Seed ': 'Field',
    'Safflower Seed Planting ': 'Field',
    'Seed Bermuda Grass ': 'Field',
    'Seed Clover Unspecified ': 'Field',
    'Seed Grass Unspecified ': 'Field',
    'Seed Other (No Flowers) ': 'Field',
    'Seed Sudan Grass ': 'Field',
    'Sunflower Seed Planting ': 'Field',
    'Hay Wild ': 'Field',
    'Hay Sudan ': 'Field',
    'Hay Other Unspecified ': 'Field',
    'Hay Green Chop ': 'Field',
    'Straw ': 'Field',
    'Field Crops Unspecified ': 'Field',
    'Corn Popcorn Seed ': 'Field',
    'Sunflower Seed ': 'Field',
    'Hops ': 'Field',
    'Seed Ladino Clover ': 'Field',
    'Seed Legumes All Other ': 'Field',
    'Seed Vetch ': 'Field',
    'Sorghum Seed ': 'Field',
    'Soybeans ': 'Field',
    'Tomatoes Fresh Market ': 'Fresh Tomatoes',
    'Tomatoes Unspecified ': 'Fresh Tomatoes',
    'Tomatoes Greenhouse ': 'Fresh Tomatoes',
    'Tomatoes Cherry ': 'Fresh Tomatoes',
    'Tomatillo ': 'Fresh Tomatoes',
    'Barley Feed ': 'Grain',
    'Barley Seed ': 'Grain',
    'Barley Unspecified ': 'Grain',
    'Corn Grain ': 'Grain',
    'Oats Grain ': 'Grain',
    'Oats Seed ': 'Grain',
    'Rye Grain ': 'Grain',
    'Rye Seed ': 'Grain',
    'Wheat All ': 'Grain',
    'Wheat Seed ': 'Grain',
    'Barley Malting ': 'Grain',
    'Garlic All ': 'Onions & Garlic',
    'Onions ': 'Onions & Garlic',
    'Onions Green & Shallot ': 'Onions & Garlic',
    'Apples All ': 'Other Deciduous',
    'Peaches Freestone ': 'Other Deciduous',
    'Peaches Clingstone ': 'Other Deciduous',
    'Peaches Unspecified ': 'Other Deciduous',
    'Cherries Sweet ': 'Other Deciduous',
    'Pears Bartlett ': 'Other Deciduous',
    'Pears Asian ': 'Other Deciduous',
    'Pears Unspecified ': 'Other Deciduous',
    'Plums ': 'Other Deciduous',
    'Plumcots ': 'Other Deciduous',
    'Plums Dried ': 'Other Deciduous',
    'Apricots All ': 'Other Deciduous',
    'Nectarines ': 'Other Deciduous',
    'Persimmons ': 'Other Deciduous',
    'Pomegranates ': 'Other Deciduous',
    'Quince ': 'Other Deciduous',
    'Cherimoyas ': 'Other Deciduous',
    'Fruits & Nuts Unspecified ': 'Other Deciduous',
    'Filberts ': 'Other Deciduous',
    'Walnuts English ': 'Other Deciduous',
    'Pecans ': 'Other Deciduous',
    'Walnuts Black ': 'Other Deciduous',
    'Chestnuts ': 'Other Deciduous',
    'Macadamia Nuts ': 'Other Deciduous',
    'Pears Prickly ': 'Other Deciduous',
    'Pasture Irrigated ': 'Pasture',
    'Pasture Forage Misc. ': 'Pasture',
    'Potatoes Irish All ': 'Potatoes',
    'Potatoes Sweet ': 'Potatoes',
    'Potatoes Seed ': 'Potatoes',
    'Tomatoes Processing ': 'Processing Tomatoes',
    'Rice Milling ': 'Rice',
    'Rice Seed ': 'Rice',
    'Rice Wild ': 'Rice',
    'Rice Sweet ': 'Rice',
    'Safflower ': 'Safflower',
    'Jojoba ': 'Subtropicals',
    'Oranges Navel ': 'Subtropicals',
    'Oranges Valencia ': 'Subtropicals',
    'Oranges Unspecified ': 'Subtropicals',
    'Grapefruit All ': 'Subtropicals',
    'Tangerines & Mandarins ': 'Subtropicals',
    'Lemons All ': 'Subtropicals',
    'Limes All ': 'Subtropicals',
    'Tangelos ': 'Subtropicals',
    'Kumquats ': 'Subtropicals',
    'Citrus By-products Misc. ': 'Subtropicals',
    'Citrus Unspecified ': 'Subtropicals',
    'Avocados All ': 'Subtropicals',
    'Dates ': 'Subtropicals',
    'Figs Dried ': 'Subtropicals',
    'Olives ': 'Subtropicals',
    'Guavas ': 'Subtropicals',
    'Kiwifruit ': 'Subtropicals',
    'Feijoa ': 'Subtropicals',
    'Pomelo ': 'Subtropicals',
    'Sugar Beets ': 'Sugar Beets',
    'Beans Lima Baby Dry ': 'Truck Crops',
    'Corn Crazy ': 'Truck Crops',
    'Corn White ': 'Truck Crops',
    'Seed Veg & Vinecrop ': 'Truck Crops',
    'Corn Popcorn ': 'Truck Crops',
    'Berries Blackberries ': 'Truck Crops',
    'Berries Boysenberries ': 'Truck Crops',
    'Berries Raspberries ': 'Truck Crops',
    'Berries Strawberries F Mkt ': 'Truck Crops',
    'Berries Strawberries Proc. ': 'Truck Crops',
    'Berries Strawberries Unspec ': 'Truck Crops',
    'Berries Blueberries ': 'Truck Crops',
    'Berries Bushberries Unspec. ': 'Truck Crops',
    'Artichokes ': 'Truck Crops',
    'Asparagus Fresh Market ': 'Truck Crops',
    'Asparagus Processing ': 'Truck Crops',
    'Asparagus Unspecified ': 'Truck Crops',
    'Beets Garden ': 'Truck Crops',
    'Peas Cowpea & Blackeye ': 'Truck Crops',
    'Peas Green Fresh Market ': 'Truck Crops',
    'Peas Green Processing ': 'Truck Crops',
    'Rappini ': 'Truck Crops',
    'Broccoli Food Service ': 'Truck Crops',
    'Broccoli Fresh Market ': 'Truck Crops',
    'Broccoli Processing ': 'Truck Crops',
    'Broccoli Unspecified ': 'Truck Crops',
    'Brussels Sprouts ': 'Truck Crops',
    'Cabbage Ch. & Specialty ': 'Truck Crops',
    'Cabbage Head ': 'Truck Crops',
    'Carrots Food Service ': 'Truck Crops',
    'Carrots Fresh Market ': 'Truck Crops',
    'Carrots Processing ': 'Truck Crops',
    'Carrots Unspecified ': 'Truck Crops',
    'Cauliflower Food Service ': 'Truck Crops',
    'Cauliflower Fresh Market ': 'Truck Crops',
    'Cauliflower Processing ': 'Truck Crops',
    'Cauliflower Unspecified ': 'Truck Crops',
    'Celery Food Service ': 'Truck Crops',
    'Celery Fresh Market ': 'Truck Crops',
    'Celery Unspecified ': 'Truck Crops',
    'Radicchio ': 'Truck Crops',
    'Collard Greens ': 'Truck Crops',
    'Corn Sweet All ': 'Truck Crops',
    'Eggplant All ': 'Truck Crops',
    'Endive All ': 'Truck Crops',
    'Escarole All ': 'Truck Crops',
    'Anise (Fennel) ': 'Truck Crops',
    'Kale ': 'Truck Crops',
    'Kohlrabi ': 'Truck Crops',
    'Lettuce Bulk Salad Prods. ': 'Truck Crops',
    'Lettuce Unspecified ': 'Truck Crops',
    'Lettuce Head ': 'Truck Crops',
    'Lettuce Romaine ': 'Truck Crops',
    'Lettuce Leaf ': 'Truck Crops',
    'Mushrooms ': 'Truck Crops',
    'Okra ': 'Truck Crops',
    'Parsley ': 'Truck Crops',
    'Parsnips ': 'Truck Crops',
    'Peas Green Unspecified ': 'Truck Crops',
    'Peppers Bell ': 'Truck Crops',
    'Peppers Chili Hot ': 'Truck Crops',
    'Pumpkins ': 'Truck Crops',
    'Radishes ': 'Truck Crops',
    'Rutabagas ': 'Truck Crops',
    'Spinach Food Service ': 'Truck Crops',
    'Spinach Fresh Market ': 'Truck Crops',
    'Spinach Processing ': 'Truck Crops',
    'Spinach Unspecified ': 'Truck Crops',
    'Swiss Chard ': 'Truck Crops',
    'Turnips All ': 'Truck Crops',
    'Greens Turnip & Mustard ': 'Truck Crops',
    'Watercress ': 'Truck Crops',
    'Leeks ': 'Truck Crops',
    'Horseradish ': 'Truck Crops',
    'Salad Greens Nec. ': 'Truck Crops',
    'Peas Edible Pod (Snow) ': 'Truck Crops',
    'Vegetables Oriental All ': 'Truck Crops',
    'Sprouts Alfalfa & Bean ': 'Truck Crops',
    'Cilantro ': 'Truck Crops',
    'Spices and Herbs ': 'Truck Crops',
    'Mint ': 'Truck Crops',
    'Vegetables Baby ': 'Truck Crops',
    'Vegetables Unspecified ': 'Truck Crops',
    'Berries Loganberries ': 'Truck Crops',
    'Berries Olallieberries ': 'Truck Crops',
    'Cabbage Red ': 'Truck Crops',
    'Cardoon ': 'Truck Crops',
    'Celery Processing ': 'Truck Crops',
    'Chives ': 'Truck Crops',
    'Mustard ': 'Truck Crops',
    'Sesame ': 'Truck Crops',
    'Taro Root ': 'Truck Crops',
    'Yucca ': 'Truck Crops',
    'Grape Table ': 'Vine',
    'Grape Wine ': 'Vine',
    'Grape Raisin ': 'Vine',
    'Grape Unspecified ': 'Vine',
}
'''
# new mapping
crop_mapping = {
    'Hay, Alfalfa, ': 'Alfalfa',
    'Hay, Alfalfa': 'Alfalfa',
    'Hay Alfalfa ': 'Alfalfa',
    'Seed, Alfalfa, ': 'Alfalfa',
    'Seed, Alfalfa': 'Alfalfa',
    'Seed Alfalfa ': 'Alfalfa',
    'Alfalfa, All, ': 'Alfalfa',
    'Alfalfa, All': 'Alfalfa',
    'Alfalfa, All ': 'Alfalfa',
    'Almond, Hulls, ': 'Almonds & Pistachios',
    'Almond, Hulls': 'Almonds & Pistachios',
    'Almond Hulls ': 'Almonds & Pistachios',
    'Almonds, All, ': 'Almonds & Pistachios',
    'Almonds, All': 'Almonds & Pistachios',
    'Almonds All ': 'Almonds & Pistachios',
    'Pistachios, ': 'Almonds & Pistachios',
    'Pistachios': 'Almonds & Pistachios',
    'Pistachios ': 'Almonds & Pistachios',
    'Corn, Silage, ': 'Corn',
    'Corn, Silage': 'Corn',
    'Corn Silage ': 'Corn',
    'Cotton, Lint, Pima, ': 'Cotton',
    'Cotton, Lint, Pima': 'Cotton',
    'Cotton Lint Pima ': 'Cotton',
    'Cotton, Lint, Unspecified, ': 'Cotton',
    'Cotton, Lint, Unspecified': 'Cotton',
    'Cotton Lint Unspecified ': 'Cotton',
    'Cotton, Lint, Upland, ': 'Cotton',
    'Cotton, Lint, Upland': 'Cotton',
    'Cotton Lint Upland ': 'Cotton',
    'Cotton, Seed, Planting, ': 'Cotton',
    'Cotton, Seed, Planting': 'Cotton',
    'Cotton Seed Planting ': 'Cotton',
    'Cottonseed, ': 'Cotton',
    'Cottonseed': 'Cotton',
    'Cottonseed ': 'Cotton',
    'Cucumbers, ': 'Cucurbits',
    'Cucumbers': 'Cucurbits',
    'Cucumbers ': 'Cucurbits',
    'Melons, Cantaloupe, ': 'Cucurbits',
    'Melons, Cantaloupe': 'Cucurbits',
    'Melons Cantaloupe ': 'Cucurbits',
    'Melons, Honeydew, ': 'Cucurbits',
    'Melons, Honeydew': 'Cucurbits',
    'Melons Honeydew ': 'Cucurbits',
    'Melons, Unspecified, ': 'Cucurbits',
    'Melons, Unspecified': 'Cucurbits',
    'Melons Unspecified ': 'Cucurbits',
    'Melons, Watermelon, ': 'Cucurbits',
    'Melons, Watermelon': 'Cucurbits',
    'Melons Watermelon ': 'Cucurbits',
    'Squash, ': 'Cucurbits',
    'Squash': 'Cucurbits',
    'Squash ': 'Cucurbits',
    'Melons, Casaba, ': 'Cucurbits',
    'Melons, Casaba': 'Cucurbits',
    'Melons Casaba ': 'Cucurbits',
    'Melons, Crenshaw, ': 'Cucurbits',
    'Melons, Crenshaw': 'Cucurbits',
    'Melons Crenshaw ': 'Cucurbits',
    'Beans, Blackeye (Peas), ': 'Dry Beans',
    'Beans, Blackeye (Peas)': 'Dry Beans',
    'Beans Blackeye (Peas) ': 'Dry Beans',
    'Beans, Dry, Edible, Unspec., ': 'Dry Beans',
    'Beans, Dry, Edible, Unspec.': 'Dry Beans',
    'Beans Dry Edible Unspec. ': 'Dry Beans',
    'Beans, Fava, ': 'Dry Beans',
    'Beans, Fava': 'Dry Beans',
    'Beans Fava ': 'Dry Beans',
    'Beans, Garbanzo, ': 'Dry Beans',
    'Beans, Garbanzo': 'Dry Beans',
    'Beans Garbanzo ': 'Dry Beans',
    'Beans, Kidney, Red, ': 'Dry Beans',
    'Beans, Kidney, Red': 'Dry Beans',
    'Beans Kidney Red ': 'Dry Beans',
    'Beans, Lima, Lg., Dry, ': 'Dry Beans',
    'Beans, Lima, Lg., Dry': 'Dry Beans',
    'Beans Lima Lg. Dry ': 'Dry Beans',
    'Beans, Lima, Unspecified, ': 'Dry Beans',
    'Beans, Lima, Unspecified': 'Dry Beans',
    'Beans Lima Unspecified ': 'Dry Beans',
    'Beans, Pink, ': 'Dry Beans',
    'Beans, Pink': 'Dry Beans',
    'Beans Pink ': 'Dry Beans',
    'Beans, Seed, ': 'Dry Beans',
    'Beans, Seed': 'Dry Beans',
    'Beans Seed ': 'Dry Beans',
    'Peas, Dry, Edible, ': 'Dry Beans',
    'Peas, Dry, Edible': 'Dry Beans',
    'Peas Dry Edible ': 'Dry Beans',
    'Beans, Lima, Green, ': 'Dry Beans',
    'Beans, Lima, Green': 'Dry Beans',
    'Beans Lima Green ': 'Dry Beans',
    'Beans, Snap, Fresh, Market, ': 'Dry Beans',
    'Beans, Snap, Fresh, Market': 'Dry Beans',
    'Beans Snap Fresh Market ': 'Dry Beans',
    'Beans, Fresh, Unspecified, ': 'Dry Beans',
    'Beans, Fresh, Unspecified': 'Dry Beans',
    'Beans Fresh Unspecified ': 'Dry Beans',
    'Beans, Snap, Unspecified, ': 'Dry Beans',
    'Beans, Snap, Unspecified': 'Dry Beans',
    'Beans Snap Unspecified ': 'Dry Beans',
    'Beans, Pinto, ': 'Dry Beans',
    'Beans, Pinto': 'Dry Beans',
    'Beans Pinto ': 'Dry Beans',
    'Beans, Red, Small, ': 'Dry Beans',
    'Beans, Red, Small': 'Dry Beans',
    'Beans Red Small ': 'Dry Beans',
    'Beans, Snap, Processing, ': 'Dry Beans',
    'Beans, Snap, Processing': 'Dry Beans',
    'Beans Snap Processing ': 'Dry Beans',
    'Beans, White, Small, ': 'Dry Beans',
    'Beans, White, Small': 'Dry Beans',
    'Beans White Small ': 'Dry Beans',
    'Beans, White, Small, Flat, ': 'Dry Beans',
    'Beans, White, Small, Flat': 'Dry Beans',
    'Beans White Small Flat ': 'Dry Beans',
    'Corn, Seed, ': 'Field',
    'Corn, Seed': 'Field',
    'Corn Seed ': 'Field',
    'Field, Crop, By-products, ': 'Field',
    'Field, Crop, By-products': 'Field',
    'Field Crop By-products ': 'Field',
    'Field, Crops, Seed, Misc., ': 'Field',
    'Field, Crops, Seed, Misc.': 'Field',
    'Field Crops Seed Misc. ': 'Field',
    'Peanuts, All, ': 'Field',
    'Peanuts, All': 'Field',
    'Peanuts All ': 'Field',
    'Peas, Seed, ': 'Field',
    'Peas, Seed': 'Field',
    'Peas Seed ': 'Field',
    'Safflower, Seed, Planting, ': 'Field',
    'Safflower, Seed, Planting': 'Field',
    'Safflower Seed Planting ': 'Field',
    'Seed, Bermuda, Grass, ': 'Field',
    'Seed, Bermuda, Grass': 'Field',
    'Seed Bermuda Grass ': 'Field',
    'Seed, Clover, Unspecified, ': 'Field',
    'Seed, Clover, Unspecified': 'Field',
    'Seed Clover Unspecified ': 'Field',
    'Seed, Grass, Unspecified, ': 'Field',
    'Seed, Grass, Unspecified': 'Field',
    'Seed Grass Unspecified ': 'Field',
    'Seed, Other (No Flowers), ': 'Field',
    'Seed, Other (No Flowers)': 'Field',
    'Seed Other (No Flowers) ': 'Field',
    'Seed, Sudan, Grass, ': 'Field',
    'Seed, Sudan, Grass': 'Field',
    'Seed Sudan Grass ': 'Field',
    'Sunflower, Seed, Planting, ': 'Field',
    'Sunflower, Seed, Planting': 'Field',
    'Sunflower Seed Planting ': 'Field',
    'Hay, Wild, ': 'Field',
    'Hay, Wild': 'Field',
    'Hay Wild ': 'Field',
    'Hay, Sudan, ': 'Field',
    'Hay, Sudan': 'Field',
    'Hay Sudan ': 'Field',
    'Hay, Other, Unspecified, ': 'Field',
    'Hay, Other, Unspecified': 'Field',
    'Hay Other Unspecified ': 'Field',
    'Hay, Green, Chop, ': 'Field',
    'Hay, Green, Chop': 'Field',
    'Hay Green Chop ': 'Field',
    'Straw, ': 'Field',
    'Straw': 'Field',
    'Straw ': 'Field',
    'Field, Crops, Unspecified, ': 'Field',
    'Field, Crops, Unspecified': 'Field',
    'Field Crops Unspecified ': 'Field',
    'Corn, Popcorn, Seed, ': 'Field',
    'Corn, Popcorn, Seed': 'Field',
    'Corn Popcorn Seed ': 'Field',
    'Sunflower, Seed, ': 'Field',
    'Sunflower, Seed': 'Field',
    'Sunflower Seed ': 'Field',
    'Hops, ': 'Field',
    'Hops': 'Field',
    'Hops ': 'Field',
    'Seed, Ladino, Clover, ': 'Field',
    'Seed, Ladino, Clover': 'Field',
    'Seed Ladino Clover ': 'Field',
    'Seed, Legumes, All, Other, ': 'Field',
    'Seed, Legumes, All, Other': 'Field',
    'Seed Legumes All Other ': 'Field',
    'Seed, Vetch, ': 'Field',
    'Seed, Vetch': 'Field',
    'Seed Vetch ': 'Field',
    'Sorghum, Seed, ': 'Field',
    'Sorghum, Seed': 'Field',
    'Sorghum Seed ': 'Field',
    'Soybeans, ': 'Field',
    'Soybeans': 'Field',
    'Soybeans ': 'Field',
    'Tomatoes, Fresh, Market, ': 'Fresh Tomatoes',
    'Tomatoes, Fresh, Market': 'Fresh Tomatoes',
    'Tomatoes Fresh Market ': 'Fresh Tomatoes',
    'Tomatoes, Unspecified, ': 'Fresh Tomatoes',
    'Tomatoes, Unspecified': 'Fresh Tomatoes',
    'Tomatoes Unspecified ': 'Fresh Tomatoes',
    'Tomatoes, Greenhouse, ': 'Fresh Tomatoes',
    'Tomatoes, Greenhouse': 'Fresh Tomatoes',
    'Tomatoes Greenhouse ': 'Fresh Tomatoes',
    'Tomatoes, Cherry, ': 'Fresh Tomatoes',
    'Tomatoes, Cherry': 'Fresh Tomatoes',
    'Tomatoes Cherry ': 'Fresh Tomatoes',
    'Tomatillo, ': 'Fresh Tomatoes',
    'Tomatillo': 'Fresh Tomatoes',
    'Tomatillo ': 'Fresh Tomatoes',
    'Barley, Feed, ': 'Grain',
    'Barley, Feed': 'Grain',
    'Barley Feed ': 'Grain',
    'Barley, Seed, ': 'Grain',
    'Barley, Seed': 'Grain',
    'Barley Seed ': 'Grain',
    'Barley, Unspecified, ': 'Grain',
    'Barley, Unspecified': 'Grain',
    'Barley Unspecified ': 'Grain',
    'Corn, Grain, ': 'Grain',
    'Corn, Grain': 'Grain',
    'Corn Grain ': 'Grain',
    'Oats, Grain, ': 'Grain',
    'Oats, Grain': 'Grain',
    'Oats Grain ': 'Grain',
    'Oats, Seed, ': 'Grain',
    'Oats, Seed': 'Grain',
    'Oats Seed ': 'Grain',
    'Rye, Grain, ': 'Grain',
    'Rye, Grain': 'Grain',
    'Rye Grain ': 'Grain',
    'Rye, Seed, ': 'Grain',
    'Rye, Seed': 'Grain',
    'Rye Seed ': 'Grain',
    'Wheat, All, ': 'Grain',
    'Wheat, All': 'Grain',
    'Wheat All ': 'Grain',
    'Wheat, Seed, ': 'Grain',
    'Wheat, Seed': 'Grain',
    'Wheat Seed ': 'Grain',
    'Barley, Malting, ': 'Grain',
    'Barley, Malting': 'Grain',
    'Barley Malting ': 'Grain',
    'Garlic, All, ': 'Onions & Garlic',
    'Garlic, All': 'Onions & Garlic',
    'Garlic All ': 'Onions & Garlic',
    'Onions, ': 'Onions & Garlic',
    'Onions': 'Onions & Garlic',
    'Onions ': 'Onions & Garlic',
    'Onions, Green, & Shallot, ': 'Onions & Garlic',
    'Onions, Green, & Shallot': 'Onions & Garlic',
    'Onions Green & Shallot ': 'Onions & Garlic',
    'Apples, All, ': 'Other Deciduous',
    'Apples, All': 'Other Deciduous',
    'Apples All ': 'Other Deciduous',
    'Peaches, Freestone, ': 'Other Deciduous',
    'Peaches, Freestone': 'Other Deciduous',
    'Peaches Freestone ': 'Other Deciduous',
    'Peaches, Clingstone, ': 'Other Deciduous',
    'Peaches, Clingstone': 'Other Deciduous',
    'Peaches Clingstone ': 'Other Deciduous',
    'Peaches, Unspecified, ': 'Other Deciduous',
    'Peaches, Unspecified': 'Other Deciduous',
    'Peaches Unspecified ': 'Other Deciduous',
    'Cherries, Sweet, ': 'Other Deciduous',
    'Cherries, Sweet': 'Other Deciduous',
    'Cherries Sweet ': 'Other Deciduous',
    'Pears, Bartlett, ': 'Other Deciduous',
    'Pears, Bartlett': 'Other Deciduous',
    'Pears Bartlett ': 'Other Deciduous',
    'Pears, Asian, ': 'Other Deciduous',
    'Pears, Asian': 'Other Deciduous',
    'Pears Asian ': 'Other Deciduous',
    'Pears, Unspecified, ': 'Other Deciduous',
    'Pears, Unspecified': 'Other Deciduous',
    'Pears Unspecified ': 'Other Deciduous',
    'Plums, ': 'Other Deciduous',
    'Plums': 'Other Deciduous',
    'Plums ': 'Other Deciduous',
    'Plumcots, ': 'Other Deciduous',
    'Plumcots': 'Other Deciduous',
    'Plumcots ': 'Other Deciduous',
    'Plums, Dried, ': 'Other Deciduous',
    'Plums, Dried': 'Other Deciduous',
    'Plums Dried ': 'Other Deciduous',
    'Apricots, All, ': 'Other Deciduous',
    'Apricots, All': 'Other Deciduous',
    'Apricots All ': 'Other Deciduous',
    'Nectarines, ': 'Other Deciduous',
    'Nectarines': 'Other Deciduous',
    'Nectarines ': 'Other Deciduous',
    'Persimmons, ': 'Other Deciduous',
    'Persimmons': 'Other Deciduous',
    'Persimmons ': 'Other Deciduous',
    'Pomegranates, ': 'Other Deciduous',
    'Pomegranates': 'Other Deciduous',
    'Pomegranates ': 'Other Deciduous',
    'Quince, ': 'Other Deciduous',
    'Quince': 'Other Deciduous',
    'Quince ': 'Other Deciduous',
    'Cherimoyas, ': 'Other Deciduous',
    'Cherimoyas': 'Other Deciduous',
    'Cherimoyas ': 'Other Deciduous',
    'Fruits, & Nuts, Unspecified, ': 'Other Deciduous',
    'Fruits, & Nuts, Unspecified': 'Other Deciduous',
    'Fruits & Nuts Unspecified ': 'Other Deciduous',
    'Filberts, ': 'Other Deciduous',
    'Filberts': 'Other Deciduous',
    'Filberts ': 'Other Deciduous',
    'Walnuts, English, ': 'Other Deciduous',
    'Walnuts, English': 'Other Deciduous',
    'Walnuts English ': 'Other Deciduous',
    'Pecans, ': 'Other Deciduous',
    'Pecans': 'Other Deciduous',
    'Pecans ': 'Other Deciduous',
    'Walnuts, Black, ': 'Other Deciduous',
    'Walnuts, Black': 'Other Deciduous',
    'Walnuts Black ': 'Other Deciduous',
    'Chestnuts, ': 'Other Deciduous',
    'Chestnuts': 'Other Deciduous',
    'Chestnuts ': 'Other Deciduous',
    'Macadamia, Nuts, ': 'Other Deciduous',
    'Macadamia, Nuts': 'Other Deciduous',
    'Macadamia Nuts ': 'Other Deciduous',
    'Pears, Prickly, ': 'Other Deciduous',
    'Pears, Prickly': 'Other Deciduous',
    'Pears Prickly ': 'Other Deciduous',
    'Pasture, Irrigated, ': 'Pasture',
    'Pasture, Irrigated': 'Pasture',
    'Pasture Irrigated ': 'Pasture',
    'Pasture, Forage, Misc., ': 'Pasture',
    'Pasture, Forage, Misc.': 'Pasture',
    'Pasture Forage Misc. ': 'Pasture',
    'Potatoes, Irish, All, ': 'Potatoes',
    'Potatoes, Irish, All': 'Potatoes',
    'Potatoes Irish All ': 'Potatoes',
    'Potatoes, Sweet, ': 'Potatoes',
    'Potatoes, Sweet': 'Potatoes',
    'Potatoes Sweet ': 'Potatoes',
    'Potatoes, Seed, ': 'Potatoes',
    'Potatoes, Seed': 'Potatoes',
    'Potatoes Seed ': 'Potatoes',
    'Tomatoes, Processing, ': 'Processing Tomatoes',
    'Tomatoes, Processing': 'Processing Tomatoes',
    'Tomatoes Processing ': 'Processing Tomatoes',
    'Rice, Milling, ': 'Rice',
    'Rice, Milling': 'Rice',
    'Rice Milling ': 'Rice',
    'Rice, Seed, ': 'Rice',
    'Rice, Seed': 'Rice',
    'Rice Seed ': 'Rice',
    'Rice, Wild, ': 'Rice',
    'Rice, Wild': 'Rice',
    'Rice Wild ': 'Rice',
    'Rice, Sweet, ': 'Rice',
    'Rice, Sweet': 'Rice',
    'Rice Sweet ': 'Rice',
    'Safflower, ': 'Safflower',
    'Safflower': 'Safflower',
    'Safflower ': 'Safflower',
    'Jojoba, ': 'Subtropicals',
    'Jojoba': 'Subtropicals',
    'Jojoba ': 'Subtropicals',
    'Oranges, Navel, ': 'Subtropicals',
    'Oranges, Navel': 'Subtropicals',
    'Oranges Navel ': 'Subtropicals',
    'Oranges, Valencia, ': 'Subtropicals',
    'Oranges, Valencia': 'Subtropicals',
    'Oranges Valencia ': 'Subtropicals',
    'Oranges, Unspecified, ': 'Subtropicals',
    'Oranges, Unspecified': 'Subtropicals',
    'Oranges Unspecified ': 'Subtropicals',
    'Grapefruit, All, ': 'Subtropicals',
    'Grapefruit, All': 'Subtropicals',
    'Grapefruit All ': 'Subtropicals',
    'Tangerines, & Mandarins, ': 'Subtropicals',
    'Tangerines, & Mandarins': 'Subtropicals',
    'Tangerines & Mandarins ': 'Subtropicals',
    'Lemons, All, ': 'Subtropicals',
    'Lemons, All': 'Subtropicals',
    'Lemons All ': 'Subtropicals',
    'Limes, All, ': 'Subtropicals',
    'Limes, All': 'Subtropicals',
    'Limes All ': 'Subtropicals',
    'Tangelos, ': 'Subtropicals',
    'Tangelos': 'Subtropicals',
    'Tangelos ': 'Subtropicals',
    'Kumquats, ': 'Subtropicals',
    'Kumquats': 'Subtropicals',
    'Kumquats ': 'Subtropicals',
    'Citrus, By-products, Misc., ': 'Subtropicals',
    'Citrus, By-products, Misc.': 'Subtropicals',
    'Citrus By-products Misc. ': 'Subtropicals',
    'Citrus, Unspecified, ': 'Subtropicals',
    'Citrus, Unspecified': 'Subtropicals',
    'Citrus Unspecified ': 'Subtropicals',
    'Avocados, All, ': 'Subtropicals',
    'Avocados, All': 'Subtropicals',
    'Avocados All ': 'Subtropicals',
    'Dates, ': 'Subtropicals',
    'Dates': 'Subtropicals',
    'Dates ': 'Subtropicals',
    'Figs, Dried, ': 'Subtropicals',
    'Figs, Dried': 'Subtropicals',
    'Figs Dried ': 'Subtropicals',
    'Olives, ': 'Subtropicals',
    'Olives': 'Subtropicals',
    'Olives ': 'Subtropicals',
    'Guavas, ': 'Subtropicals',
    'Guavas': 'Subtropicals',
    'Guavas ': 'Subtropicals',
    'Kiwifruit, ': 'Subtropicals',
    'Kiwifruit': 'Subtropicals',
    'Kiwifruit ': 'Subtropicals',
    'Feijoa, ': 'Subtropicals',
    'Feijoa': 'Subtropicals',
    'Feijoa ': 'Subtropicals',
    'Pomelo, ': 'Subtropicals',
    'Pomelo': 'Subtropicals',
    'Pomelo ': 'Subtropicals',
    'Sugar, Beets, ': 'Sugar Beets',
    'Sugar, Beets': 'Sugar Beets',
    'Sugar Beets ': 'Sugar Beets',
    'Beans, Lima, Baby, Dry, ': 'Truck Crops',
    'Beans, Lima, Baby, Dry': 'Truck Crops',
    'Beans Lima Baby Dry ': 'Truck Crops',
    'Corn, Crazy, ': 'Truck Crops',
    'Corn, Crazy': 'Truck Crops',
    'Corn Crazy ': 'Truck Crops',
    'Corn, White, ': 'Truck Crops',
    'Corn, White': 'Truck Crops',
    'Corn White ': 'Truck Crops',
    'Seed, Veg, & Vinecrop, ': 'Truck Crops',
    'Seed, Veg, & Vinecrop': 'Truck Crops',
    'Seed Veg & Vinecrop ': 'Truck Crops',
    'Corn, Popcorn, ': 'Truck Crops',
    'Corn, Popcorn': 'Truck Crops',
    'Corn Popcorn ': 'Truck Crops',
    'Berries, Blackberries, ': 'Truck Crops',
    'Berries, Blackberries': 'Truck Crops',
    'Berries Blackberries ': 'Truck Crops',
    'Berries, Boysenberries, ': 'Truck Crops',
    'Berries, Boysenberries': 'Truck Crops',
    'Berries Boysenberries ': 'Truck Crops',
    'Berries, Raspberries, ': 'Truck Crops',
    'Berries, Raspberries': 'Truck Crops',
    'Berries Raspberries ': 'Truck Crops',
    'Berries, Strawberries, F, Mkt, ': 'Truck Crops',
    'Berries, Strawberries, F, Mkt': 'Truck Crops',
    'Berries Strawberries F Mkt ': 'Truck Crops',
    'Berries, Strawberries, Proc., ': 'Truck Crops',
    'Berries, Strawberries, Proc.': 'Truck Crops',
    'Berries Strawberries Proc. ': 'Truck Crops',
    'Berries, Strawberries, Unspec, ': 'Truck Crops',
    'Berries, Strawberries, Unspec': 'Truck Crops',
    'Berries Strawberries Unspec ': 'Truck Crops',
    'Berries, Blueberries, ': 'Truck Crops',
    'Berries, Blueberries': 'Truck Crops',
    'Berries Blueberries ': 'Truck Crops',
    'Berries, Bushberries, Unspec., ': 'Truck Crops',
    'Berries, Bushberries, Unspec.': 'Truck Crops',
    'Berries Bushberries Unspec. ': 'Truck Crops',
    'Artichokes, ': 'Truck Crops',
    'Artichokes': 'Truck Crops',
    'Artichokes ': 'Truck Crops',
    'Asparagus, Fresh, Market, ': 'Truck Crops',
    'Asparagus, Fresh, Market': 'Truck Crops',
    'Asparagus Fresh Market ': 'Truck Crops',
    'Asparagus, Processing, ': 'Truck Crops',
    'Asparagus, Processing': 'Truck Crops',
    'Asparagus Processing ': 'Truck Crops',
    'Asparagus, Unspecified, ': 'Truck Crops',
    'Asparagus, Unspecified': 'Truck Crops',
    'Asparagus Unspecified ': 'Truck Crops',
    'Beets, Garden, ': 'Truck Crops',
    'Beets, Garden': 'Truck Crops',
    'Beets Garden ': 'Truck Crops',
    'Peas, Cowpea, & Blackeye, ': 'Truck Crops',
    'Peas, Cowpea, & Blackeye': 'Truck Crops',
    'Peas Cowpea & Blackeye ': 'Truck Crops',
    'Peas, Green, Fresh, Market, ': 'Truck Crops',
    'Peas, Green, Fresh, Market': 'Truck Crops',
    'Peas Green Fresh Market ': 'Truck Crops',
    'Peas, Green, Processing, ': 'Truck Crops',
    'Peas, Green, Processing': 'Truck Crops',
    'Peas Green Processing ': 'Truck Crops',
    'Rappini, ': 'Truck Crops',
    'Rappini': 'Truck Crops',
    'Rappini ': 'Truck Crops',
    'Broccoli, Food, Service, ': 'Truck Crops',
    'Broccoli, Food, Service': 'Truck Crops',
    'Broccoli Food Service ': 'Truck Crops',
    'Broccoli, Fresh, Market, ': 'Truck Crops',
    'Broccoli, Fresh, Market': 'Truck Crops',
    'Broccoli Fresh Market ': 'Truck Crops',
    'Broccoli, Processing, ': 'Truck Crops',
    'Broccoli, Processing': 'Truck Crops',
    'Broccoli Processing ': 'Truck Crops',
    'Broccoli, Unspecified, ': 'Truck Crops',
    'Broccoli, Unspecified': 'Truck Crops',
    'Broccoli Unspecified ': 'Truck Crops',
    'Brussels, Sprouts, ': 'Truck Crops',
    'Brussels, Sprouts': 'Truck Crops',
    'Brussels Sprouts ': 'Truck Crops',
    'Cabbage, Ch., & Specialty, ': 'Truck Crops',
    'Cabbage, Ch., & Specialty': 'Truck Crops',
    'Cabbage Ch. & Specialty ': 'Truck Crops',
    'Cabbage, Head, ': 'Truck Crops',
    'Cabbage, Head': 'Truck Crops',
    'Cabbage Head ': 'Truck Crops',
    'Carrots, Food, Service, ': 'Truck Crops',
    'Carrots, Food, Service': 'Truck Crops',
    'Carrots Food Service ': 'Truck Crops',
    'Carrots, Fresh, Market, ': 'Truck Crops',
    'Carrots, Fresh, Market': 'Truck Crops',
    'Carrots Fresh Market ': 'Truck Crops',
    'Carrots, Processing, ': 'Truck Crops',
    'Carrots, Processing': 'Truck Crops',
    'Carrots Processing ': 'Truck Crops',
    'Carrots, Unspecified, ': 'Truck Crops',
    'Carrots, Unspecified': 'Truck Crops',
    'Carrots Unspecified ': 'Truck Crops',
    'Cauliflower, Food, Service, ': 'Truck Crops',
    'Cauliflower, Food, Service': 'Truck Crops',
    'Cauliflower Food Service ': 'Truck Crops',
    'Cauliflower, Fresh, Market, ': 'Truck Crops',
    'Cauliflower, Fresh, Market': 'Truck Crops',
    'Cauliflower Fresh Market ': 'Truck Crops',
    'Cauliflower, Processing, ': 'Truck Crops',
    'Cauliflower, Processing': 'Truck Crops',
    'Cauliflower Processing ': 'Truck Crops',
    'Cauliflower, Unspecified, ': 'Truck Crops',
    'Cauliflower, Unspecified': 'Truck Crops',
    'Cauliflower Unspecified ': 'Truck Crops',
    'Celery, Food, Service, ': 'Truck Crops',
    'Celery, Food, Service': 'Truck Crops',
    'Celery Food Service ': 'Truck Crops',
    'Celery, Fresh, Market, ': 'Truck Crops',
    'Celery, Fresh, Market': 'Truck Crops',
    'Celery Fresh Market ': 'Truck Crops',
    'Celery, Unspecified, ': 'Truck Crops',
    'Celery, Unspecified': 'Truck Crops',
    'Celery Unspecified ': 'Truck Crops',
    'Radicchio, ': 'Truck Crops',
    'Radicchio': 'Truck Crops',
    'Radicchio ': 'Truck Crops',
    'Collard, Greens, ': 'Truck Crops',
    'Collard, Greens': 'Truck Crops',
    'Collard Greens ': 'Truck Crops',
    'Corn, Sweet, All, ': 'Truck Crops',
    'Corn, Sweet, All': 'Truck Crops',
    'Corn Sweet All ': 'Truck Crops',
    'Eggplant, All, ': 'Truck Crops',
    'Eggplant, All': 'Truck Crops',
    'Eggplant All ': 'Truck Crops',
    'Endive, All, ': 'Truck Crops',
    'Endive, All': 'Truck Crops',
    'Endive All ': 'Truck Crops',
    'Escarole, All, ': 'Truck Crops',
    'Escarole, All': 'Truck Crops',
    'Escarole All ': 'Truck Crops',
    'Anise, (Fennel), ': 'Truck Crops',
    'Anise, (Fennel)': 'Truck Crops',
    'Anise (Fennel) ': 'Truck Crops',
    'Kale, ': 'Truck Crops',
    'Kale': 'Truck Crops',
    'Kale ': 'Truck Crops',
    'Kohlrabi, ': 'Truck Crops',
    'Kohlrabi': 'Truck Crops',
    'Kohlrabi ': 'Truck Crops',
    'Lettuce, Bulk, Salad, Prods., ': 'Truck Crops',
    'Lettuce, Bulk, Salad, Prods.': 'Truck Crops',
    'Lettuce Bulk Salad Prods. ': 'Truck Crops',
    'Lettuce, Unspecified, ': 'Truck Crops',
    'Lettuce, Unspecified': 'Truck Crops',
    'Lettuce Unspecified ': 'Truck Crops',
    'Lettuce, Head, ': 'Truck Crops',
    'Lettuce, Head': 'Truck Crops',
    'Lettuce Head ': 'Truck Crops',
    'Lettuce, Romaine, ': 'Truck Crops',
    'Lettuce, Romaine': 'Truck Crops',
    'Lettuce Romaine ': 'Truck Crops',
    'Lettuce, Leaf, ': 'Truck Crops',
    'Lettuce, Leaf': 'Truck Crops',
    'Lettuce Leaf ': 'Truck Crops',
    'Mushrooms, ': 'Truck Crops',
    'Mushrooms': 'Truck Crops',
    'Mushrooms ': 'Truck Crops',
    'Okra, ': 'Truck Crops',
    'Okra': 'Truck Crops',
    'Okra ': 'Truck Crops',
    'Parsley, ': 'Truck Crops',
    'Parsley': 'Truck Crops',
    'Parsley ': 'Truck Crops',
    'Parsnips, ': 'Truck Crops',
    'Parsnips': 'Truck Crops',
    'Parsnips ': 'Truck Crops',
    'Peas, Green, Unspecified, ': 'Truck Crops',
    'Peas, Green, Unspecified': 'Truck Crops',
    'Peas Green Unspecified ': 'Truck Crops',
    'Peppers, Bell, ': 'Truck Crops',
    'Peppers, Bell': 'Truck Crops',
    'Peppers Bell ': 'Truck Crops',
    'Peppers, Chili, Hot, ': 'Truck Crops',
    'Peppers, Chili, Hot': 'Truck Crops',
    'Peppers Chili Hot ': 'Truck Crops',
    'Pumpkins, ': 'Truck Crops',
    'Pumpkins': 'Truck Crops',
    'Pumpkins ': 'Truck Crops',
    'Radishes, ': 'Truck Crops',
    'Radishes': 'Truck Crops',
    'Radishes ': 'Truck Crops',
    'Rutabagas, ': 'Truck Crops',
    'Rutabagas': 'Truck Crops',
    'Rutabagas ': 'Truck Crops',
    'Spinach, Food, Service, ': 'Truck Crops',
    'Spinach, Food, Service': 'Truck Crops',
    'Spinach Food Service ': 'Truck Crops',
    'Spinach, Fresh, Market, ': 'Truck Crops',
    'Spinach, Fresh, Market': 'Truck Crops',
    'Spinach Fresh Market ': 'Truck Crops',
    'Spinach, Processing, ': 'Truck Crops',
    'Spinach, Processing': 'Truck Crops',
    'Spinach Processing ': 'Truck Crops',
    'Spinach, Unspecified, ': 'Truck Crops',
    'Spinach, Unspecified': 'Truck Crops',
    'Spinach Unspecified ': 'Truck Crops',
    'Swiss, Chard, ': 'Truck Crops',
    'Swiss, Chard': 'Truck Crops',
    'Swiss Chard ': 'Truck Crops',
    'Turnips, All, ': 'Truck Crops',
    'Turnips, All': 'Truck Crops',
    'Turnips All ': 'Truck Crops',
    'Greens, Turnip, & Mustard, ': 'Truck Crops',
    'Greens, Turnip, & Mustard': 'Truck Crops',
    'Greens Turnip & Mustard ': 'Truck Crops',
    'Watercress, ': 'Truck Crops',
    'Watercress': 'Truck Crops',
    'Watercress ': 'Truck Crops',
    'Leeks, ': 'Truck Crops',
    'Leeks': 'Truck Crops',
    'Leeks ': 'Truck Crops',
    'Horseradish, ': 'Truck Crops',
    'Horseradish': 'Truck Crops',
    'Horseradish ': 'Truck Crops',
    'Salad, Greens, Nec., ': 'Truck Crops',
    'Salad, Greens, Nec.': 'Truck Crops',
    'Salad Greens Nec. ': 'Truck Crops',
    'Peas, Edible, Pod, (Snow), ': 'Truck Crops',
    'Peas, Edible, Pod, (Snow)': 'Truck Crops',
    'Peas Edible Pod (Snow) ': 'Truck Crops',
    'Vegetables, Oriental, All, ': 'Truck Crops',
    'Vegetables, Oriental, All': 'Truck Crops',
    'Vegetables Oriental All ': 'Truck Crops',
    'Sprouts, Alfalfa, & Bean, ': 'Truck Crops',
    'Sprouts, Alfalfa, & Bean': 'Truck Crops',
    'Sprouts Alfalfa & Bean ': 'Truck Crops',
    'Cilantro, ': 'Truck Crops',
    'Cilantro': 'Truck Crops',
    'Cilantro ': 'Truck Crops',
    'Spices, and, Herbs, ': 'Truck Crops',
    'Spices, and, Herbs': 'Truck Crops',
    'Spices and Herbs ': 'Truck Crops',
    'Mint, ': 'Truck Crops',
    'Mint': 'Truck Crops',
    'Mint ': 'Truck Crops',
    'Vegetables, Baby, ': 'Truck Crops',
    'Vegetables, Baby': 'Truck Crops',
    'Vegetables Baby ': 'Truck Crops',
    'Vegetables, Unspecified, ': 'Truck Crops',
    'Vegetables, Unspecified': 'Truck Crops',
    'Vegetables Unspecified ': 'Truck Crops',
    'Berries, Loganberries, ': 'Truck Crops',
    'Berries, Loganberries': 'Truck Crops',
    'Berries Loganberries ': 'Truck Crops',
    'Berries, Olallieberries, ': 'Truck Crops',
    'Berries, Olallieberries': 'Truck Crops',
    'Berries Olallieberries ': 'Truck Crops',
    'Cabbage, Red, ': 'Truck Crops',
    'Cabbage, Red': 'Truck Crops',
    'Cabbage Red ': 'Truck Crops',
    'Cardoon, ': 'Truck Crops',
    'Cardoon': 'Truck Crops',
    'Cardoon ': 'Truck Crops',
    'Celery, Processing, ': 'Truck Crops',
    'Celery, Processing': 'Truck Crops',
    'Celery Processing ': 'Truck Crops',
    'Chives, ': 'Truck Crops',
    'Chives': 'Truck Crops',
    'Chives ': 'Truck Crops',
    'Mustard, ': 'Truck Crops',
    'Mustard': 'Truck Crops',
    'Mustard ': 'Truck Crops',
    'Sesame, ': 'Truck Crops',
    'Sesame': 'Truck Crops',
    'Sesame ': 'Truck Crops',
    'Taro, Root, ': 'Truck Crops',
    'Taro, Root': 'Truck Crops',
    'Taro Root ': 'Truck Crops',
    'Yucca, ': 'Truck Crops',
    'Yucca': 'Truck Crops',
    'Yucca ': 'Truck Crops',
    'Grape, Table, ': 'Vine',
    'Grape, Table': 'Vine',
    'Grape Table ': 'Vine',
    'Grape, Wine, ': 'Vine',
    'Grape, Wine': 'Vine',
    'Grape Wine ': 'Vine',
    'Grape, Raisin, ': 'Vine',
    'Grape, Raisin': 'Vine',
    'Grape Raisin ': 'Vine',
    'Grape, Unspecified, ': 'Vine',
    'Grape, Unspecified': 'Vine',
    'Grape Unspecified ': 'Vine',
}
    


if __name__ == '__main__':
    # Read the original CSV file with low_memory=False to handle mixed types
    df = pd.read_csv('capitalized_combined.csv', low_memory=False)
    
    # Get the name of the second column
    crop_column = df.columns[2]
    print(f"Using column: {crop_column}")
    
    # Make a copy of the dataframe
    df_new = df.copy()
    
    # Map the values using the second column
    df_new[crop_column] = df[crop_column].map(crop_mapping)
    
    # Print unique values from the column after mapping, handling NaN values
    unique_values = df_new[crop_column].unique()
    # Remove NaN values and sort
    unique_values = sorted([x for x in unique_values if pd.notna(x)])
    
    print("\nUnique values after mapping:")
    print(unique_values)
    
    # Export to new CSV file
    output_filename = 'mapped_combineddata_2024_3.csv'
    df_new.to_csv(output_filename, index=False)
    print(f"\nData exported to {output_filename}")